# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('peptidedb_id', models.CharField(max_length=250)),
                ('uniprot_id', models.CharField(max_length=250)),
                ('endonet_link', models.CharField(max_length=250)),
                ('know_fragments', models.BooleanField(default=False)),
                ('hormone', models.BooleanField(default=False)),
                ('pro_peptide', models.BooleanField(default=False)),
                ('transcript', models.BooleanField(default=False)),
                ('peptide_name', models.CharField(max_length=250)),
                ('fasta', models.TextField(default='')),
            ],
        ),
    ]
